name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install WASM tools
        run: dotnet workload install wasm-tools-net9

      - name: Restore
        run: dotnet restore ./ImageCreatePlaid.csproj

      - name: Publish
        run: dotnet publish ./ImageCreatePlaid.csproj -c Release -o release

      - name: Prepare GitHub Pages
        shell: bash
        run: |
          REPOSITORY_NAME="${GITHUB_REPOSITORY#*/}"

          sed -i "s|<base href=\"/\" />|<base href=\"/$REPOSITORY_NAME/\" />|g" release/wwwroot/index.html

          touch release/wwwroot/.nojekyll

          cp release/wwwroot/index.html release/wwwroot/404.html

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: release/wwwroot

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4